### PR TITLE
Add configuration for Travis-CI

### PR DESCRIPTION
**Pull request by jawnsy**
Signed-off-by: Jonathan Yu <jawnsy@redhat.com>

### CODE REVIEW

**Comment by jawnsy** [comment]
Example Travis build is here: https://travis-ci.org/jawnsy/sti-wildfly/builds/114409072

**Comment by bparees** [comment]
Can you explain what this buys us over our existing jenkins PR testing process, given that we're taking on additional maintenance to add this configuration?

@mfojtik fyi

**Comment by jawnsy** [comment]
Oh, I didn't realize we had this covered in our Jenkins tests. I'd suggest that we should at least add a status badge to show the current build state & to make the Jenkins dashboard more discoverable.

I guess the advantages I could think of are:

1. Consistency with openshift/origin, which builds on Travis CI
2. Builds occur outside our infrastructure, operated & maintained by the good folks at Travis CI
3. There appears to be better console log display support on Travis, for example the Jenkins build has lots of lines like this: `1546/1886 KB   432/510 KB` and by contrast the Travis display looks similar to what you would see in a terminal
4. The maintenance cost (also updating .travis.yml) is pretty small (how often do we have to update the Jenkins build?). Additionally, having this file means external users can contribute suggestions (PRs) for the builds.
5. This build provides additional testing coverage (ensures the image is buildable on Ubuntu) - I'm assuming our Jenkins builds use Fedora/RHEL/CentOS

Not sure how compelling this is, though.

**Comment by bparees** [comment]
in origin we do a lighter weight test via travis as compared to what jenkins runs.  that doesn't appear to be the case here, you're just running the exact same tests in two different places.

but we can give it a shot and see how it goes.  I just don't want to be debugging flakes caused by travis having issues.

**Comment by jawnsy** [comment]
I guess someone with permission for our org needs to flip the switch in the Travis console as well. Can you do that, @bparees?

**Comment by bparees** [comment]
I don't have that permission as far as i know.  @danmcp probably does.

**Comment by danmcp** [comment]
@bparees @jawnsy Done

**Pull request merged**
