### PR TITLE
Download archives using https

### PR DESCRIPTION
**Pull request by jawnsy**
This change also combines consecutive ENV calls to reduce layers created during the build.

Signed-off-by: Jonathan Yu <jawnsy@redhat.com>

### CODE REVIEW

**Comment by bparees** [comment]
@rhcarvalho your changes to vagrant-openshift appear to have broken the PR tester:
```
+ git fetch origin pull/fc6e25ea2a26ade258101e2e2d33c08c92c67ac8/head:fc6e25ea2a26ade258101e2e2d33c08c92c67ac8
fatal: Couldn't find remote ref pull/fc6e25ea2a26ade258101e2e2d33c08c92c67ac8/head
```

**Comment by bparees** [comment]
link to build failure:
https://ci.openshift.redhat.com/jenkins/job/sti-wildfly/73/

**Comment by bparees** [comment]
reverted changes in vagrant-openshift
[test]

**Comment by bparees** [comment]
@jawnsy the new failure appears legit (cert problems using https)

**Comment by rhcarvalho** [comment]
> @rhcarvalho your changes to vagrant-openshift appear to have broken the PR tester:

@bparees hmm, sorry, so it looks like, against my belief and understanding, `ref` is a commit hash and not the PR number :(

How am I supposed to test changes to the tester next time?

**Comment by bparees** [comment]
you have to install the plugin (w/ your changes) locally and then invoke it (basically following the steps the PR tester job does to instantiate an ec2 instance and run the vagrant commands against it).

it's a bit trickier in this case since you're relying on input from the jenkins git plugin.

**Comment by jawnsy** [comment]
The cause of the problem was that the server (www.us.apache.org) presents a certificate for *.apache.org, and wildcard certificates only apply for one level (so the certificate is valid for www.apache.org but not www.us.apache.org.) I could've sworn that I tested this locally and achieved a successful build, but I guess not.

I updated the URLs accordingly (switching to https://www.apache.org - presumably internal geolocation logic will direct us to the "best" mirror?)

Additionally, I added `-v` to make the `curl` command output verbose information about the certificates it encounters, which will allow us to more easily debug problems of this nature in the future. I also removed the `-0` flag (that's a zero, not a capital letter O) because this forces HTTP/1.0, which is probably not what we want.

**Comment by bparees** [comment]
lgtm.

**Pull request merged**
