### PR TITLE
Fix sti build url in README

### PR DESCRIPTION
**Pull request by nak3**

### CODE REVIEW

**Comment by bparees** [comment]
What's the purpose of this change? What you've provided is not the URL of a buildable source repository.

**Comment by nak3** [comment]
Sorry, it was my copy&paste mistake. Please take a look.

I updated:

* URL points to this repository's example : `https://github.com/openshift/sti-wildfly.git`
* Image name : `openshift/wildfly-81-centos7`

**Comment by nak3** [comment]
Sorry again. After I re-considered my change, it looks better to fix only image name. I sent the update.

**Comment by bparees** [comment]
lgtm.  thanks.

**Pull request merged**
