### PR TITLE
added base wildfly 10.0.0CR4 configuration

### PR DESCRIPTION
**Pull request by phil-pona**
Hi,

I added the Wildlfy 10 (10.0.0CR4) configuration.
If you wish to only have final versions on the main repository you can close the Pull Request and I'll wait until the Final Version of the Wildfly 10 is out and make a new Pull Request.

Thanks and regards

### CODE REVIEW

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
will take a closer look at it on monday, i'm ok with merging the release candidate.

**Comment by bparees** [comment]
thanks for the pull, the new image should be on dockerhub in an hour or so:
https://hub.docker.com/r/openshift/wildfly-10-centos7/

**Comment by bparees** [comment]
make that https://hub.docker.com/r/openshift/wildfly-100-centos7/

**Comment by phil-pona** [comment]
Thanks!

**Pull request merged**
