### PR TITLE
sti -> s2i rebranding

### PR DESCRIPTION
**Pull request by soltysh**

### CODE REVIEW

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
looks like you missed a .sti change in this one.

**Comment by bparees** [comment]
line 13 of test/run

**Comment by soltysh** [comment]
Actually that line should not contain script location so I removed it, since in the base image we set the `io.openshift.s2i.scripts-url=image:///usr/local/sti` and in wildfly's dockerfile we copy s2i scripts there. So it should use the built in ones. I'm guessing this comes from prehistorical times :wink: when we had our image pointing to git repo and not scripts inside the image.

**Pull request merged**
